### ISSUE TITLE
ocdrnet.py line 116

### ISSUE THREAD

**Issue by JohnTan38** [NVIDIA/metropolis-nim-workflows#2]
AttributeError: module 'os' has no attribute 'sync'
Please advise how to fix this. Thank you.

**Comment by ssmmoo1** [comment]
Hi John, 

What operating system and python version are you on? 

You can delete line 116 ```os.sync``` from ocdrnet.py and then try running again. 
This line is there to ensure the file changes are flushed to disk but is not strictly needed.

**Comment by JohnTan38** [comment]
> Hi John,
> 
> What operating system and python version are you on?
> 
> You can delete line 116 `os.sync` from ocdrnet.py and then try running again. This line is there to ensure the file changes are flushed to disk but is not strictly needed.

Hi
yes commented out line 116 os.sync(). understand this is for Linux, macOS systems.
Windows, Python 3.12.
will try executing code and update, if any queries. thank you for this excellent app. I'm a newbie to AI software engineering and NVDA generative AI is a great platform to start learning.
